server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/usermanagementms4?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   
    hibernate:
      ddl-auto: update
app:
    jwt:
        secret: yourSuperSecretKeyThatIsAtLeast512BitsLongForHS256AlgorithmSecurity
        expirationMs: 86400000
application:
    name: USER MANAGEMENT-SERVICE
  